import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import {
  Bai_Jamjuree as BaiJamjuree,
  Roboto_Flex as Roboto,
} from "next/font/google";
import LeftComponent from "./components/LeftComponent/LeftComponent";
import AuthProvider from "./components/authprovider/authprovider";
import "./globals.css";

const roboto = Roboto({ subsets: ["latin"], variable: "--font-roboto" });
const baiJamjuree = BaiJamjuree({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-bai-jamjuree",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${roboto.variable} ${baiJamjuree.variable} font-sans w-full h-full bg-zinc-900 text-gray-200 `
        )}
      >
        <AuthProvider>
          <div className="flex flex-row">
            <div className="w-[40%] h-screen">
              <LeftComponent />
            </div>
            <div className="w-full"> {children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
